# coding: utf-8

"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import io
from typing import Mapping, Optional

from aiohttp import ClientResponse as RESTResponseType


class RESTResponse(io.IOBase):
    def __init__(self, resp: RESTResponseType) -> None:
        self.response = resp
        self.status = resp.status
        self.reason = resp.reason
        self.data: Optional[bytes] = None

    def read(self) -> bytes:
        if self.data is None:
            self.data = self.response.data
        return self.data

    def getheaders(self) -> Mapping[str, str]:
        """Returns a dictionary of the response headers."""
        return self.response.headers

    def getheader(self, name: str, default: Optional[str]=None) -> Optional[str]:
        """Returns a given response header."""
        return self.response.headers.get(name, default)
