# coding: utf-8

"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models.
    Please do not use this for any other purpose. Special characters: \" \\  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pytest

import petstore_api


@pytest.mark.asyncio
async def test_call_123_test_special_tags():
    """Test case for call_123_test_special_tags

    To test special tags  # noqa: E501
    """
    petstore_api.api.another_fake_api.AnotherFakeApi()  # noqa: E501
