name: Python Server

on:
  pull_request:
    paths:
      - samples/server/petstore/python-aiohttp/**
      - .github/workflows/samples-python-server.yaml

jobs:
  build:
    name: Test Python server
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        sample:
          # servers
          - samples/server/petstore/python-aiohttp/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test
        working-directory: ${{ matrix.sample }}
        run: make test-all
